CREATE DATABASE IF NOT EXISTS CORE;

USE CORE;

CREATE TABLE IF NOT EXISTS ORGANIZATION (
	ORGANIZATION_ID					INT NOT NULL AUTO_INCREMENT,
	ORGANIZATION_NAME				VARCHAR(100) NOT NULL,
	ORGANIZATION_ALIAS				VARCHAR(50),
	ORGANIZATION_ADDRESS_1			VARCHAR(200),
	ORGANIZATION_ADDRESS_2			VARCHAR(200),
	ORGANIZATION_CITY				VARCHAR(100),
	ORGANIZATION_DISTRICT			VARCHAR(100),
	ORGANIZATION_STATE				VARCHAR(100),
	ORGANIZATION_COUNTRY			VARCHAR(100),
	ORGANIZATION_PIN				VARCHAR(6),
	ORGANIZATION_PRIMARY_PHONE		VARCHAR(30),
	ORGANIZATION_PRIMARY_FAX		VARCHAR(30),
	ORGANIZATION_PRIMARY_EMAIL		VARCHAR(100),
	ORGANIZATION_ALTERNATE_PHONE	VARCHAR(30),
	ORGANIZATION_ALTERNATE_FAX		VARCHAR(30),
	ORGANIZATION_ALTERNATE_EMAIL	VARCHAR(100),
	ORGANIZATION_STATUS				INT(2),
	ORGANIZATION_CREATION_STAMP		DATETIME NOT NULL,
	ORGANIZATION_CREATED_BY			INT,
	ORGANIZATION_UPDATED_STAMP		DATETIME NOT NULL,
	ORGANIZATION_UPDATED_BY			INT,
	PRIMARY KEY (ORGANIZATION_ID)
);

/*CREATE TABLE IF NOT EXISTS ORGANIZATION_CONTACT (
	ORG_CONTACT_ID					INT NOT NULL AUTO_INCREMENT,
	ORGANIZATION_ID					INT NOT NULL,
	ORG_CONTACT_ACCESS_KEY			VARCHAR(50) NOT NULL UNIQUE,
	ORG_CONTACT_TYPE				INT NOT NULL,
	ORG_CONTACT_TITLE				VARCHAR(100) NOT NULL,
	ORG_CONTACT_FIRST_NAME			VARCHAR(100) NOT NULL,
	ORG_CONTACT_MIDDLE_NAME			VARCHAR(100) NOT NULL,
	ORG_CONTACT_LAST_NAME			VARCHAR(100) NOT NULL,
	ORG_CONTACT_PREFERRED_NAME		VARCHAR(100),
	ORG_CONTACT_DESIGNATION			VARCHAR(100),
	ORG_CONTACT_ADDRESS_1			VARCHAR(200) NOT NULL,
	ORG_CONTACT_ADDRESS_2			VARCHAR(200),
	ORG_CONTACT_CITY				VARCHAR(100),
	ORG_CONTACT_DISTRICT			VARCHAR(100),
	ORG_CONTACT_STATE				VARCHAR(100),
	ORG_CONTACT_COUNTRY				VARCHAR(100),
	ORG_CONTACT_PIN					VARCHAR(6),
	ORG_CONTACT_PRIMARY_PHONE		VARCHAR(30),
	ORG_CONTACT_PRIMARY_FAX			VARCHAR(30),
	ORG_CONTACT_PRIMARY_EMAIL		VARCHAR(100),
	ORG_CONTACT_ALTERNATE_PHONE		VARCHAR(30),
	ORG_CONTACT_ALTERNATE_FAX		VARCHAR(30),
	ORG_CONTACT_ALTERNATE_EMAIL		VARCHAR(100),
	ORG_CONTACT_CREATION_STAMP		TIMESTAMP NOT NULL DEFAULT NOW(),
	ORG_CONTACT_UPDATED_STAMP		TIMESTAMP NOT NULL,
	ORG_CONTACT_UPDATED_BY			INT,
	PRIMARY KEY (ORG_CONTACT_ID)
);
*/